title: Familiar Fonts
description: Welcome to Familiar Fonts! We explore some of the most recognisable
  fonts in the world, explain why they are effective and how they coordinate
  with and represent their given brand! Enjoy!
header_text: ""
footer_text: Copyright 2020 Lloyd Canfield
header_feature_image: ../uploads/copy-of-untitled-4-.png
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
