title: FamiliarFonts
description: Welcome to Familiar Fonts! We explore some of the most recognisable
  fonts in the world, explain why they are effective and how they coordinate
  with and represent their given brand! Enjoy!
header_text: ""
footer_text: Copyright 2020 Lloyd Canfield
header_feature_image: ../uploads/game-on.png
bannerheight: 20vmax
logo: ../uploads/favicon.ico
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items:
  - name: About Lloyd Canfield
    siteurl: /aboutme
    tab: true
