title: FamiliarFonts
description: Welcome to Familiar Fonts! We explore some of the most recognisable
  fonts in the world, explain why they are effective and how they coordinate
  with and represent their given brand! Enjoy!
header_text: Familiar Fonts
footer_text: Copyright 2020 Lloyd Canfield
header_feature_image: ../uploads/familiar-fonts-1-.png
bannerheight: 20vmax
logo: ../uploads/crafts-paperie.png
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
